### ISSUE TITLE
Metrics that disappear are still reported until exporter restart

### ISSUE THREAD

**Issue by robvalca** [cern-eos/eos_exporter#23]
For the metrics that have the posibility to dissapear, for example, nodes or filesystems that get removed, values are still taken into account until the restart of the exporter.  This can be fixed calling .Reset() before the collection, like we do [here](https://github.com/cern-eos/eos_exporter/blob/8bf184f3535d1967711583066162ded043a6754c/collector/who.go#L93)

**Comment by mariayh1** [comment]
This affecting eosversions queries, filesystems status or nodes.
