### ISSUE TITLE
Missing eos_fs_boot_status for all filesystems except one

### ISSUE THREAD

**Issue by koziomek** [cern-eos/eos_exporter#28]
Value of the  metric `eos_fs_boot_status` is missing for all but one of the filesystems.
All other fs metrics look fine.

Exported metrics: [metrics.txt](https://github.com/cern-eos/eos_exporter/files/13305348/metrics.txt)
Output of `eos fs ls -m`: [eos_fs_ls_m.txt](https://github.com/cern-eos/eos_exporter/files/13305349/eos_fs_ls_m.txt)

Could it have something to do with it being the first metric in the export output?

**Comment by robvalca** [comment]
Hi @koziomek, 
Thanks for reporting, will have a look we also have the same problem.
Which version of EOS are you using?
Cheers,

**Comment by koziomek** [comment]
Hello,

I can confirm the fix is working. Thanks!
